export const SERVICE_CONFIG = {
  CHATBOT: {
    MAX_RETRIES: import.meta.env.VITE_CHATBOT_MAX_RETRIES || 2,
    MAX_FAILURES_BEFORE_FALLBACK: import.meta.env.VITE_CHATBOT_MAX_FAILURES || 10,
    RATE_LIMIT_WINDOW_MS: import.meta.env.VITE_CHATBOT_RATE_LIMIT_MS || 60000,
    RATE_LIMIT_BUFFER_MS: import.meta.env.VITE_CHATBOT_RATE_LIMIT_BUFFER || 5000,
    RETRY_INITIAL_DELAY_MS: import.meta.env.VITE_CHATBOT_RETRY_DELAY || 2000,
    RETRY_MAX_DELAY_MS: import.meta.env.VITE_CHATBOT_RETRY_MAX_DELAY || 30000,
    CONVERSATION_HISTORY_LIMIT: import.meta.env.VITE_CHATBOT_HISTORY_LIMIT || 20,
  },
  GROQ: {
    CHAT: {
      MAX_TOKENS: import.meta.env.VITE_GROQ_CHAT_MAX_TOKENS || 2048,
      TEMPERATURE: import.meta.env.VITE_GROQ_CHAT_TEMPERATURE || 0.9,
      TOP_P: import.meta.env.VITE_GROQ_CHAT_TOP_P || 0.95,
    },
    RECOMMENDATIONS: {
      MAX_TOKENS: import.meta.env.VITE_GROQ_REC_MAX_TOKENS || 1024,
      TEMPERATURE: import.meta.env.VITE_GROQ_REC_TEMPERATURE || 0.3,
    },
  },
  SEARCH: {
    RESULTS_LIMIT: import.meta.env.VITE_SEARCH_RESULTS_LIMIT || 20,
  },
  NOTIFICATIONS: {
    FETCH_LIMIT: import.meta.env.VITE_NOTIFICATIONS_FETCH_LIMIT || 20,
  },
  STORAGE: {
    SIGNED_URL_EXPIRY_SECONDS: import.meta.env.VITE_STORAGE_URL_EXPIRY || 3600,
  },
};
